package Tables;
// Generated 17-Jul-2024 12:43:50 by Hibernate Tools 4.3.1



/**
 * Appstats generated by hbm2java
 */
public class Appstats  implements java.io.Serializable {


     private int id;
     private long sessioncount;

    public Appstats() {
    }

    public Appstats(int id, long sessioncount) {
       this.id = id;
       this.sessioncount = sessioncount;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public long getSessioncount() {
        return this.sessioncount;
    }
    
    public void setSessioncount(long sessioncount) {
        this.sessioncount = sessioncount;
    }




}


