package Tables;
// Generated 17-Jul-2024 12:43:50 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Bid generated by hbm2java
 */
public class Bid  implements java.io.Serializable {


     private BidId id;
     private Participant participant;
     private Registration registration;
     private double ammount;
     private Date date;
     private int status;

    public Bid() {
    }

    public Bid(BidId id, Participant participant, Registration registration, double ammount, Date date, int status) {
       this.id = id;
       this.participant = participant;
       this.registration = registration;
       this.ammount = ammount;
       this.date = date;
       this.status = status;
    }
   
    public BidId getId() {
        return this.id;
    }
    
    public void setId(BidId id) {
        this.id = id;
    }
    public Participant getParticipant() {
        return this.participant;
    }
    
    public void setParticipant(Participant participant) {
        this.participant = participant;
    }
    public Registration getRegistration() {
        return this.registration;
    }
    
    public void setRegistration(Registration registration) {
        this.registration = registration;
    }
    public double getAmmount() {
        return this.ammount;
    }
    
    public void setAmmount(double ammount) {
        this.ammount = ammount;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


