package Tables;
// Generated 17-Jul-2024 12:43:50 by Hibernate Tools 4.3.1



/**
 * BidId generated by hbm2java
 */
public class BidId  implements java.io.Serializable {


     private long idParticipant;
     private long idRegistration;

    public BidId() {
    }

    public BidId(long idParticipant, long idRegistration) {
       this.idParticipant = idParticipant;
       this.idRegistration = idRegistration;
    }
   
    public long getIdParticipant() {
        return this.idParticipant;
    }
    
    public void setIdParticipant(long idParticipant) {
        this.idParticipant = idParticipant;
    }
    public long getIdRegistration() {
        return this.idRegistration;
    }
    
    public void setIdRegistration(long idRegistration) {
        this.idRegistration = idRegistration;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BidId) ) return false;
		 BidId castOther = ( BidId ) other; 
         
		 return (this.getIdParticipant()==castOther.getIdParticipant())
 && (this.getIdRegistration()==castOther.getIdRegistration());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getIdParticipant();
         result = 37 * result + (int) this.getIdRegistration();
         return result;
   }   


}


