package Tables;
// Generated 17-Jul-2024 12:43:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Car generated by hbm2java
 */
public class Car  implements java.io.Serializable {


     private Long id;
     private Participant participant;
     private String nickname;
     private double weight;
     private double width;
     private String description;
     private Set<Registration> registrations = new HashSet<Registration>(0);

    public Car() {
    }

	
    public Car(Participant participant, String nickname, double weight, double width) {
        this.participant = participant;
        this.nickname = nickname;
        this.weight = weight;
        this.width = width;
    }
    public Car(Participant participant, String nickname, double weight, double width, String description, Set<Registration> registrations) {
       this.participant = participant;
       this.nickname = nickname;
       this.weight = weight;
       this.width = width;
       this.description = description;
       this.registrations = registrations;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Participant getParticipant() {
        return this.participant;
    }
    
    public void setParticipant(Participant participant) {
        this.participant = participant;
    }
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }
    public double getWeight() {
        return this.weight;
    }
    
    public void setWeight(double weight) {
        this.weight = weight;
    }
    public double getWidth() {
        return this.width;
    }
    
    public void setWidth(double width) {
        this.width = width;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set<Registration> getRegistrations() {
        return this.registrations;
    }
    
    public void setRegistrations(Set<Registration> registrations) {
        this.registrations = registrations;
    }




}


