package Tables;
// Generated 17-Jul-2024 12:43:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Countryregion generated by hbm2java
 */
public class Countryregion  implements java.io.Serializable {


     private Long id;
     private Country country;
     private String name;
     private long idCreator;
     private Set<Province> provinces = new HashSet<Province>(0);

    public Countryregion() {
    }

	
    public Countryregion(Country country, String name, long idCreator) {
        this.country = country;
        this.name = name;
        this.idCreator = idCreator;
    }
    public Countryregion(Country country, String name, long idCreator, Set<Province> provinces) {
       this.country = country;
       this.name = name;
       this.idCreator = idCreator;
       this.provinces = provinces;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public long getIdCreator() {
        return this.idCreator;
    }
    
    public void setIdCreator(long idCreator) {
        this.idCreator = idCreator;
    }
    public Set<Province> getProvinces() {
        return this.provinces;
    }
    
    public void setProvinces(Set<Province> provinces) {
        this.provinces = provinces;
    }




}


