package Tables;
// Generated 17-Jul-2024 12:43:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Country generated by hbm2java
 */
public class Country  implements java.io.Serializable {


     private Long id;
     private Planetregion planetregion;
     private String name;
     private long idCreator;
     private Set<Countryregion> countryregions = new HashSet<Countryregion>(0);

    public Country() {
    }

	
    public Country(Planetregion planetregion, String name, long idCreator) {
        this.planetregion = planetregion;
        this.name = name;
        this.idCreator = idCreator;
    }
    public Country(Planetregion planetregion, String name, long idCreator, Set<Countryregion> countryregions) {
       this.planetregion = planetregion;
       this.name = name;
       this.idCreator = idCreator;
       this.countryregions = countryregions;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Planetregion getPlanetregion() {
        return this.planetregion;
    }
    
    public void setPlanetregion(Planetregion planetregion) {
        this.planetregion = planetregion;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public long getIdCreator() {
        return this.idCreator;
    }
    
    public void setIdCreator(long idCreator) {
        this.idCreator = idCreator;
    }
    public Set<Countryregion> getCountryregions() {
        return this.countryregions;
    }
    
    public void setCountryregions(Set<Countryregion> countryregions) {
        this.countryregions = countryregions;
    }




}


