package Tables;
// Generated 17-Jul-2024 12:43:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Currency generated by hbm2java
 */
public class Currency  implements java.io.Serializable {


     private int id;
     private String code;
     private String name;
     private double dollarvalue;
     private String symbol;
     private Set<Regatta> regattas = new HashSet<Regatta>(0);

    public Currency() {
    }

	
    public Currency(int id, String code, String name, double dollarvalue, String symbol) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.dollarvalue = dollarvalue;
        this.symbol = symbol;
    }
    public Currency(int id, String code, String name, double dollarvalue, String symbol, Set<Regatta> regattas) {
       this.id = id;
       this.code = code;
       this.name = name;
       this.dollarvalue = dollarvalue;
       this.symbol = symbol;
       this.regattas = regattas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public double getDollarvalue() {
        return this.dollarvalue;
    }
    
    public void setDollarvalue(double dollarvalue) {
        this.dollarvalue = dollarvalue;
    }
    public String getSymbol() {
        return this.symbol;
    }
    
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }
    public Set<Regatta> getRegattas() {
        return this.regattas;
    }
    
    public void setRegattas(Set<Regatta> regattas) {
        this.regattas = regattas;
    }




}


