// src/main/java/Tables/Participant.java
// Hibernate entity for TOP Racing account identity and operational status.
package Tables;
// Generated 17-Jul-2024 12:43:50 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Participant generated by hbm2java
 */
public class Participant  implements java.io.Serializable {

     public static final String PAYPAL_STATUS_UNVERIFIED = "UNVERIFIED";
     public static final String PAYPAL_STATUS_USABLE = "USABLE";
     public static final String PAYPAL_STATUS_ONBOARDING_STARTED = "ONBOARDING_STARTED";
     public static final String PAYPAL_STATUS_PERMISSION_DENIED = "PERMISSION_DENIED";
     public static final String PAYPAL_STATUS_REMOTE_PENDING = "REMOTE_PENDING";
     public static final String PAYPAL_STATUS_VERIFICATION_FAILED = "VERIFICATION_FAILED";
     public static final String CURRENT_TERMS_VERSION = "SRS-2.7-2026-08-14";
     public static final String CURRENT_TERMS_EFFECTIVE_DATE = "2026-08-14";

     private Long id;
     private Venue venue;
     private String password;
     private String namesGiven;
     private String namesFamily;
     private String email;
     private String phone;
     private String emailKey;
     private boolean emailConfirmed;
     private boolean paypalUsable;
     private String paypalPayerId;
     private String paypalMerchantId;
     private String paypalStatus;
     private Date confirmedAt;
     private Date paypalVerifiedAt;
     private String termsVersionAccepted;
     private Date termsAcceptedAt;
     private boolean confirmed;
     private int defaulter;
     private Set<Pointscount> pointscounts = new HashSet<Pointscount>(0);
     private Set<Registration> registrationsForIdBuyer = new HashSet<Registration>(0);
     private Set<Regatta> regattas = new HashSet<Regatta>(0);
     private Set<Venue> venues = new HashSet<Venue>(0);
     private Set<Registration> registrationsForIdDriver = new HashSet<Registration>(0);
     private Set<Registration> registrationsForIdOwner = new HashSet<Registration>(0);
     private Set<Car> cars = new HashSet<Car>(0);
     private Set<Bid> bids = new HashSet<Bid>(0);

    public Participant() {
    }

	
    public Participant(Venue venue, String password, String namesGiven, String namesFamily, String email, String phone, String emailKey, boolean confirmed, int defaulter) {
        this.venue = venue;
        this.password = password;
        this.namesGiven = namesGiven;
        this.namesFamily = namesFamily;
        this.email = email;
        this.phone = phone;
        this.emailKey = emailKey;
        this.setConfirmed( confirmed );
        this.defaulter = defaulter;
    }
    public Participant(Venue venue, String password, String namesGiven, String namesFamily, String email, String phone, String emailKey, boolean confirmed, int defaulter, Set<Pointscount> pointscounts, Set<Registration> registrationsForIdBuyer, Set<Regatta> regattas, Set<Venue> venues, Set<Registration> registrationsForIdDriver, Set<Registration> registrationsForIdOwner, Set<Car> cars, Set<Bid> bids) {
       this.venue = venue;
       this.password = password;
       this.namesGiven = namesGiven;
       this.namesFamily = namesFamily;
       this.email = email;
       this.phone = phone;
       this.emailKey = emailKey;
       this.setConfirmed( confirmed );
       this.defaulter = defaulter;
       this.pointscounts = pointscounts;
       this.registrationsForIdBuyer = registrationsForIdBuyer;
       this.regattas = regattas;
       this.venues = venues;
       this.registrationsForIdDriver = registrationsForIdDriver;
       this.registrationsForIdOwner = registrationsForIdOwner;
       this.cars = cars;
       this.bids = bids;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Venue getVenue() {
        return this.venue;
    }
    
    public void setVenue(Venue venue) {
        this.venue = venue;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNamesGiven() {
        return this.namesGiven;
    }
    
    public void setNamesGiven(String namesGiven) {
        this.namesGiven = namesGiven;
    }
    public String getNamesFamily() {
        return this.namesFamily;
    }
    
    public void setNamesFamily(String namesFamily) {
        this.namesFamily = namesFamily;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmailKey() {
        return this.emailKey;
    }
    
    public void setEmailKey(String emailKey) {
        this.emailKey = emailKey;
    }
    public boolean isEmailConfirmed() {
        return this.emailConfirmed;
    }
    
    public void setEmailConfirmed(boolean emailConfirmed) {
        this.emailConfirmed = emailConfirmed;
    }
    public boolean isPaypalUsable() {
        return this.paypalUsable;
    }
    
    public void setPaypalUsable(boolean paypalUsable) {
        this.paypalUsable = paypalUsable;
        if( paypalUsable ) {
            if( this.paypalStatus == null
                || PAYPAL_STATUS_UNVERIFIED.equals( this.paypalStatus ) ) {
                this.paypalStatus = PAYPAL_STATUS_USABLE;
            }
            if( this.paypalVerifiedAt == null ) {
                this.paypalVerifiedAt = new Date();
            }
            return;
        }
        if( this.paypalStatus == null
            || PAYPAL_STATUS_USABLE.equals( this.paypalStatus ) ) {
            this.paypalStatus = PAYPAL_STATUS_UNVERIFIED;
        }
        this.paypalVerifiedAt = null;
    }
    public String getPaypalPayerId() {
        return this.paypalPayerId;
    }
    
    public void setPaypalPayerId(String paypalPayerId) {
        this.paypalPayerId = paypalPayerId;
    }
    public String getPaypalMerchantId() {
        return this.paypalMerchantId;
    }
    
    public void setPaypalMerchantId(String paypalMerchantId) {
        this.paypalMerchantId = paypalMerchantId;
    }
    public String getPaypalStatus() {
        return this.paypalStatus;
    }
    
    public void setPaypalStatus(String paypalStatus) {
        this.paypalStatus = paypalStatus;
    }
    public Date getConfirmedAt() {
        return this.confirmedAt;
    }
    
    public void setConfirmedAt(Date confirmedAt) {
        this.confirmedAt = confirmedAt;
    }
    public Date getPaypalVerifiedAt() {
        return this.paypalVerifiedAt;
    }
    
    public void setPaypalVerifiedAt(Date paypalVerifiedAt) {
        this.paypalVerifiedAt = paypalVerifiedAt;
    }
    public String getTermsVersionAccepted() {
        return this.termsVersionAccepted;
    }

    public void setTermsVersionAccepted(String termsVersionAccepted) {
        this.termsVersionAccepted = termsVersionAccepted;
    }
    public Date getTermsAcceptedAt() {
        return this.termsAcceptedAt;
    }

    public void setTermsAcceptedAt(Date termsAcceptedAt) {
        this.termsAcceptedAt = termsAcceptedAt;
    }
    public void acceptCurrentTerms() {
        this.termsVersionAccepted = CURRENT_TERMS_VERSION;
        this.termsAcceptedAt = new Date();
    }
    public boolean hasAcceptedCurrentTerms() {
        return CURRENT_TERMS_VERSION.equals( this.termsVersionAccepted )
               && this.termsAcceptedAt != null;
    }
    public boolean isConfirmed() {
        return this.confirmed;
    }
    
    public void setConfirmed(boolean confirmed) {
        this.confirmed = confirmed;
        if( confirmed ) {
            this.emailConfirmed = true;
            this.setPaypalUsable( true );
            if( this.confirmedAt == null ) {
                this.confirmedAt = new Date();
            }
            return;
        }
        this.confirmedAt = null;
    }
    public void refreshOperationalConfirmation() {
        this.confirmed = this.emailConfirmed
                         && this.paypalUsable;
        if( this.confirmed && this.confirmedAt == null ) {
            this.confirmedAt = new Date();
        }
        if( !this.confirmed ) {
            this.confirmedAt = null;
        }
    }
    public int getDefaulter() {
        return this.defaulter;
    }
    
    public void setDefaulter(int defaulter) {
        this.defaulter = defaulter;
    }
    public Set<Pointscount> getPointscounts() {
        return this.pointscounts;
    }
    
    public void setPointscounts(Set<Pointscount> pointscounts) {
        this.pointscounts = pointscounts;
    }
    public Set<Registration> getRegistrationsForIdBuyer() {
        return this.registrationsForIdBuyer;
    }
    
    public void setRegistrationsForIdBuyer(Set<Registration> registrationsForIdBuyer) {
        this.registrationsForIdBuyer = registrationsForIdBuyer;
    }
    public Set<Regatta> getRegattas() {
        return this.regattas;
    }
    
    public void setRegattas(Set<Regatta> regattas) {
        this.regattas = regattas;
    }
    public Set<Venue> getVenues() {
        return this.venues;
    }
    
    public void setVenues(Set<Venue> venues) {
        this.venues = venues;
    }
    public Set<Registration> getRegistrationsForIdDriver() {
        return this.registrationsForIdDriver;
    }
    
    public void setRegistrationsForIdDriver(Set<Registration> registrationsForIdDriver) {
        this.registrationsForIdDriver = registrationsForIdDriver;
    }
    public Set<Registration> getRegistrationsForIdOwner() {
        return this.registrationsForIdOwner;
    }
    
    public void setRegistrationsForIdOwner(Set<Registration> registrationsForIdOwner) {
        this.registrationsForIdOwner = registrationsForIdOwner;
    }
    public Set<Car> getCars() {
        return this.cars;
    }
    
    public void setCars(Set<Car> cars) {
        this.cars = cars;
    }
    public Set<Bid> getBids() {
        return this.bids;
    }
    
    public void setBids(Set<Bid> bids) {
        this.bids = bids;
    }




}
