package Tables;
// Generated 17-Jul-2024 12:43:50 by Hibernate Tools 4.3.1


/**
 * Penaltiespl generated by hbm2java
 */
public class Penaltiespl  implements java.io.Serializable {


     private PenaltiesplId id;
     private Regatta regatta;
     private int value0;
     private int value1;
     private int value2;
     private int value3;
     private int value4;
     private int value5;
     private int value6;
     private int value7;

    public Penaltiespl() {
    }

    public Penaltiespl(PenaltiesplId id, Regatta regatta, int value0, int value1, int value2, int value3, int value4, int value5, int value6, int value7) {
       this.id = id;
       this.regatta = regatta;
       this.value0 = value0;
       this.value1 = value1;
       this.value2 = value2;
       this.value3 = value3;
       this.value4 = value4;
       this.value5 = value5;
       this.value6 = value6;
       this.value7 = value7;
    }
   
    public PenaltiesplId getId() {
        return this.id;
    }
    
    public void setId(PenaltiesplId id) {
        this.id = id;
    }
    public Regatta getRegatta() {
        return this.regatta;
    }
    
    public void setRegatta(Regatta regatta) {
        this.regatta = regatta;
    }
    public int getValue0() {
        return this.value0;
    }
    
    public void setValue0(int value0) {
        this.value0 = value0;
    }
    public int getValue1() {
        return this.value1;
    }
    
    public void setValue1(int value1) {
        this.value1 = value1;
    }
    public int getValue2() {
        return this.value2;
    }
    
    public void setValue2(int value2) {
        this.value2 = value2;
    }
    public int getValue3() {
        return this.value3;
    }
    
    public void setValue3(int value3) {
        this.value3 = value3;
    }
    public int getValue4() {
        return this.value4;
    }
    
    public void setValue4(int value4) {
        this.value4 = value4;
    }
    public int getValue5() {
        return this.value5;
    }
    
    public void setValue5(int value5) {
        this.value5 = value5;
    }
    public int getValue6() {
        return this.value6;
    }
    
    public void setValue6(int value6) {
        this.value6 = value6;
    }
    public int getValue7() {
        return this.value7;
    }
    
    public void setValue7(int value7) {
        this.value7 = value7;
    }




}
