package Tables;
// Generated 17-Jul-2024 12:43:50 by Hibernate Tools 4.3.1


/**
 * PenaltiesplId generated by hbm2java
 */
public class PenaltiesplId  implements java.io.Serializable {


     private long idRegatta;
     private int levelPeriod;

    public PenaltiesplId() {
    }

    public PenaltiesplId(long idRegatta, int levelPeriod) {
       this.idRegatta = idRegatta;
       this.levelPeriod = levelPeriod;
    }
   
    public long getIdRegatta() {
        return this.idRegatta;
    }
    
    public void setIdRegatta(long idRegatta) {
        this.idRegatta = idRegatta;
    }
    public int getLevelPeriod() {
        return this.levelPeriod;
    }
    
    public void setLevelPeriod(int levelPeriod) {
        this.levelPeriod = levelPeriod;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PenaltiesplId) ) return false;
		 PenaltiesplId castOther = ( PenaltiesplId ) other; 
         
		 return (this.getIdRegatta()==castOther.getIdRegatta())
 && (this.getLevelPeriod()==castOther.getLevelPeriod());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getIdRegatta();
         result = 37 * result + this.getLevelPeriod();
         return result;
   }   


}
