package Tables;
// Generated 17-Jul-2024 12:43:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Planetregion generated by hbm2java
 */
public class Planetregion  implements java.io.Serializable {


     private Long id;
     private String name;
     private long idCreator;
     private Set<Country> countries = new HashSet<Country>(0);

    public Planetregion() {
    }

	
    public Planetregion(String name, long idCreator) {
        this.name = name;
        this.idCreator = idCreator;
    }
    public Planetregion(String name, long idCreator, Set<Country> countries) {
       this.name = name;
       this.idCreator = idCreator;
       this.countries = countries;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public long getIdCreator() {
        return this.idCreator;
    }
    
    public void setIdCreator(long idCreator) {
        this.idCreator = idCreator;
    }
    public Set<Country> getCountries() {
        return this.countries;
    }
    
    public void setCountries(Set<Country> countries) {
        this.countries = countries;
    }




}


