package Tables;
// Generated 17-Jul-2024 12:43:50 by Hibernate Tools 4.3.1


/**
 * PointscountId generated by hbm2java
 */
public class PointscountId  implements java.io.Serializable {


     private long idParticipant;
     private int levelPeriod;
     private long idPeriod;
     private int levelTrackset;
     private long idTrackset;

    public PointscountId() {
    }

    public PointscountId(long idParticipant, int levelPeriod, long idPeriod, int levelTrackset, long idTrackset) {
       this.idParticipant = idParticipant;
       this.levelPeriod = levelPeriod;
       this.idPeriod = idPeriod;
       this.levelTrackset = levelTrackset;
       this.idTrackset = idTrackset;
    }
   
    public long getIdParticipant() {
        return this.idParticipant;
    }
    
    public void setIdParticipant(long idParticipant) {
        this.idParticipant = idParticipant;
    }
    public int getLevelPeriod() {
        return this.levelPeriod;
    }
    
    public void setLevelPeriod(int levelPeriod) {
        this.levelPeriod = levelPeriod;
    }
    public long getIdPeriod() {
        return this.idPeriod;
    }
    
    public void setIdPeriod(long idPeriod) {
        this.idPeriod = idPeriod;
    }
    public int getLevelTrackset() {
        return this.levelTrackset;
    }
    
    public void setLevelTrackset(int levelTrackset) {
        this.levelTrackset = levelTrackset;
    }
    public long getIdTrackset() {
        return this.idTrackset;
    }
    
    public void setIdTrackset(long idTrackset) {
        this.idTrackset = idTrackset;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PointscountId) ) return false;
		 PointscountId castOther = ( PointscountId ) other; 
         
		 return (this.getIdParticipant()==castOther.getIdParticipant())
 && (this.getLevelPeriod()==castOther.getLevelPeriod())
 && (this.getIdPeriod()==castOther.getIdPeriod())
 && (this.getLevelTrackset()==castOther.getLevelTrackset())
 && (this.getIdTrackset()==castOther.getIdTrackset());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getIdParticipant();
         result = 37 * result + this.getLevelPeriod();
         result = 37 * result + (int) this.getIdPeriod();
         result = 37 * result + this.getLevelTrackset();
         result = 37 * result + (int) this.getIdTrackset();
         return result;
   }   


}
