package Tables;
// Generated 17-Jul-2024 12:43:50 by Hibernate Tools 4.3.1



/**
 * Pointscount generated by hbm2java
 */
public class Pointscount  implements java.io.Serializable {


     private PointscountId id;
     private Participant participant;
     private double pointsSD;
     private double pointsSO;
     private double pointsRD;
     private double pointsRO;
     private double pointsED;
     private double pointsEO;

    public Pointscount() {
    }

    public Pointscount(PointscountId id, Participant participant, double pointsSD, double pointsSO, double pointsRD, double pointsRO, double pointsED, double pointsEO) {
       this.id = id;
       this.participant = participant;
       this.pointsSD = pointsSD;
       this.pointsSO = pointsSO;
       this.pointsRD = pointsRD;
       this.pointsRO = pointsRO;
       this.pointsED = pointsED;
       this.pointsEO = pointsEO;
    }
   
    public PointscountId getId() {
        return this.id;
    }
    
    public void setId(PointscountId id) {
        this.id = id;
    }
    public Participant getParticipant() {
        return this.participant;
    }
    
    public void setParticipant(Participant participant) {
        this.participant = participant;
    }
    public double getPointsSD() {
        return this.pointsSD;
    }
    
    public void setPointsSD(double pointsSD) {
        this.pointsSD = pointsSD;
    }
    public double getPointsSO() {
        return this.pointsSO;
    }
    
    public void setPointsSO(double pointsSO) {
        this.pointsSO = pointsSO;
    }
    public double getPointsRD() {
        return this.pointsRD;
    }
    
    public void setPointsRD(double pointsRD) {
        this.pointsRD = pointsRD;
    }
    public double getPointsRO() {
        return this.pointsRO;
    }
    
    public void setPointsRO(double pointsRO) {
        this.pointsRO = pointsRO;
    }
    public double getPointsED() {
        return this.pointsED;
    }
    
    public void setPointsED(double pointsED) {
        this.pointsED = pointsED;
    }
    public double getPointsEO() {
        return this.pointsEO;
    }
    
    public void setPointsEO(double pointsEO) {
        this.pointsEO = pointsEO;
    }




}


