package Tables;
// Generated 17-Jul-2024 12:43:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Provinceregion generated by hbm2java
 */
public class Provinceregion  implements java.io.Serializable {


     private Long id;
     private Province province;
     private String name;
     private long idCreator;
     private Set<Venue> venues = new HashSet<Venue>(0);

    public Provinceregion() {
    }

	
    public Provinceregion(Province province, String name, long idCreator) {
        this.province = province;
        this.name = name;
        this.idCreator = idCreator;
    }
    public Provinceregion(Province province, String name, long idCreator, Set<Venue> venues) {
       this.province = province;
       this.name = name;
       this.idCreator = idCreator;
       this.venues = venues;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Province getProvince() {
        return this.province;
    }
    
    public void setProvince(Province province) {
        this.province = province;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public long getIdCreator() {
        return this.idCreator;
    }
    
    public void setIdCreator(long idCreator) {
        this.idCreator = idCreator;
    }
    public Set<Venue> getVenues() {
        return this.venues;
    }
    
    public void setVenues(Set<Venue> venues) {
        this.venues = venues;
    }




}


