package Tables;
// Generated 17-Jul-2024 12:43:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Province generated by hbm2java
 */
public class Province  implements java.io.Serializable {


     private Long id;
     private Countryregion countryregion;
     private String name;
     private long idCreator;
     private Set<Provinceregion> provinceregions = new HashSet<Provinceregion>(0);

    public Province() {
    }

	
    public Province(Countryregion countryregion, String name, long idCreator) {
        this.countryregion = countryregion;
        this.name = name;
        this.idCreator = idCreator;
    }
    public Province(Countryregion countryregion, String name, long idCreator, Set<Provinceregion> provinceregions) {
       this.countryregion = countryregion;
       this.name = name;
       this.idCreator = idCreator;
       this.provinceregions = provinceregions;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Countryregion getCountryregion() {
        return this.countryregion;
    }
    
    public void setCountryregion(Countryregion countryregion) {
        this.countryregion = countryregion;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public long getIdCreator() {
        return this.idCreator;
    }
    
    public void setIdCreator(long idCreator) {
        this.idCreator = idCreator;
    }
    public Set<Provinceregion> getProvinceregions() {
        return this.provinceregions;
    }
    
    public void setProvinceregions(Set<Provinceregion> provinceregions) {
        this.provinceregions = provinceregions;
    }




}


