package Tables;
// Generated 17-Jul-2024 12:43:50 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Regatta generated by hbm2java
 */
public class Regatta  implements java.io.Serializable {


     private Long id;
     private Currency currency;
     private Participant participant;
     private Variant variant;
     private int maxWeight;
     private int minLoad;
     private Date datetime;
     private int minutesSpeed;
     private int minutesRace;
     private double entryfee;
     private double trackrental;
     private double prizeFinishing;
     private double prizeEfficiency;
     private int maxQualifiers;
     private byte status;
     private String colorFg;
     private String colorBg;
     private int levelPeriod;
     private int levelTrackset;
     private double slope;
     private double intercept;
     private int validregistrations;
     private Set<Penaltiespl> penaltiespls = new HashSet<Penaltiespl>(0);
     private Set<Registration> registrations = new HashSet<Registration>(0);

    public Regatta() {
    }

	
    public Regatta(Participant participant, Variant variant, int maxWeight, int minLoad, Date datetime, int minutesSpeed, int minutesRace, double entryfee, double trackrental, double prizeFinishing, double prizeEfficiency, int maxQualifiers, byte status, int levelPeriod, int levelTrackset, double slope, double intercept, int validregistrations) {
        this.participant = participant;
        this.variant = variant;
        this.maxWeight = maxWeight;
        this.minLoad = minLoad;
        this.datetime = datetime;
        this.minutesSpeed = minutesSpeed;
        this.minutesRace = minutesRace;
        this.entryfee = entryfee;
        this.trackrental = trackrental;
        this.prizeFinishing = prizeFinishing;
        this.prizeEfficiency = prizeEfficiency;
        this.maxQualifiers = maxQualifiers;
        this.status = status;
        this.levelPeriod = levelPeriod;
        this.levelTrackset = levelTrackset;
        this.slope = slope;
        this.intercept = intercept;
        this.validregistrations = validregistrations;
    }
    public Regatta(Currency currency, Participant participant, Variant variant, int maxWeight, int minLoad, Date datetime, int minutesSpeed, int minutesRace, double entryfee, double trackrental, double prizeFinishing, double prizeEfficiency, int maxQualifiers, byte status, String colorFg, String colorBg, int levelPeriod, int levelTrackset, double slope, double intercept, int validregistrations, Set<Penaltiespl> penaltiespls, Set<Registration> registrations) {
       this.currency = currency;
       this.participant = participant;
       this.variant = variant;
       this.maxWeight = maxWeight;
       this.minLoad = minLoad;
       this.datetime = datetime;
       this.minutesSpeed = minutesSpeed;
       this.minutesRace = minutesRace;
       this.entryfee = entryfee;
       this.trackrental = trackrental;
       this.prizeFinishing = prizeFinishing;
       this.prizeEfficiency = prizeEfficiency;
       this.maxQualifiers = maxQualifiers;
       this.status = status;
       this.colorFg = colorFg;
       this.colorBg = colorBg;
       this.levelPeriod = levelPeriod;
       this.levelTrackset = levelTrackset;
       this.slope = slope;
       this.intercept = intercept;
       this.validregistrations = validregistrations;
       this.penaltiespls = penaltiespls;
       this.registrations = registrations;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Currency getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(Currency currency) {
        this.currency = currency;
    }
    public Participant getParticipant() {
        return this.participant;
    }
    
    public void setParticipant(Participant participant) {
        this.participant = participant;
    }
    public Variant getVariant() {
        return this.variant;
    }
    
    public void setVariant(Variant variant) {
        this.variant = variant;
    }
    public int getMaxWeight() {
        return this.maxWeight;
    }
    
    public void setMaxWeight(int maxWeight) {
        this.maxWeight = maxWeight;
    }
    public int getMinLoad() {
        return this.minLoad;
    }
    
    public void setMinLoad(int minLoad) {
        this.minLoad = minLoad;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
    public int getMinutesSpeed() {
        return this.minutesSpeed;
    }
    
    public void setMinutesSpeed(int minutesSpeed) {
        this.minutesSpeed = minutesSpeed;
    }
    public int getMinutesRace() {
        return this.minutesRace;
    }
    
    public void setMinutesRace(int minutesRace) {
        this.minutesRace = minutesRace;
    }
    public double getEntryfee() {
        return this.entryfee;
    }
    
    public void setEntryfee(double entryfee) {
        this.entryfee = entryfee;
    }
    public double getTrackrental() {
        return this.trackrental;
    }
    
    public void setTrackrental(double trackrental) {
        this.trackrental = trackrental;
    }
    public double getPrizeFinishing() {
        return this.prizeFinishing;
    }
    
    public void setPrizeFinishing(double prizeFinishing) {
        this.prizeFinishing = prizeFinishing;
    }
    public double getPrizeEfficiency() {
        return this.prizeEfficiency;
    }
    
    public void setPrizeEfficiency(double prizeEfficiency) {
        this.prizeEfficiency = prizeEfficiency;
    }
    public int getMaxQualifiers() {
        return this.maxQualifiers;
    }
    
    public void setMaxQualifiers(int maxQualifiers) {
        this.maxQualifiers = maxQualifiers;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    public String getColorFg() {
        return this.colorFg;
    }
    
    public void setColorFg(String colorFg) {
        this.colorFg = colorFg;
    }
    public String getColorBg() {
        return this.colorBg;
    }
    
    public void setColorBg(String colorBg) {
        this.colorBg = colorBg;
    }
    public int getLevelPeriod() {
        return this.levelPeriod;
    }
    
    public void setLevelPeriod(int levelPeriod) {
        this.levelPeriod = levelPeriod;
    }
    public int getLevelTrackset() {
        return this.levelTrackset;
    }
    
    public void setLevelTrackset(int levelTrackset) {
        this.levelTrackset = levelTrackset;
    }
    public double getSlope() {
        return this.slope;
    }
    
    public void setSlope(double slope) {
        this.slope = slope;
    }
    public double getIntercept() {
        return this.intercept;
    }
    
    public void setIntercept(double intercept) {
        this.intercept = intercept;
    }
    public int getValidregistrations() {
        return this.validregistrations;
    }
    
    public void setValidregistrations(int validregistrations) {
        this.validregistrations = validregistrations;
    }
    public Set<Penaltiespl> getPenaltiespls() {
        return this.penaltiespls;
    }
    
    public void setPenaltiespls(Set<Penaltiespl> penaltiespls) {
        this.penaltiespls = penaltiespls;
    }
    public Set<Registration> getRegistrations() {
        return this.registrations;
    }
    
    public void setRegistrations(Set<Registration> registrations) {
        this.registrations = registrations;
    }




}


