package Tables;
// Generated 17-Jul-2024 12:43:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Registration generated by hbm2java
 */
public class Registration  implements java.io.Serializable {


     private Long id;
     private Car car;
     private Participant participantByIdBuyer;
     private Participant participantByIdDriver;
     private Participant participantByIdOwner;
     private Regatta regatta;
     private double betEfficiency;
     private double betFinishing;
     private double secondsLap;
     private short posSpeed;
     private short posRacegrid;
     private short posRace;
     private short lapsRace;
     private double prizeFinishing;
     private double valueAuction;
     private double valueBase;
     private short posEfficiency;
     private double prizeEfficiency;
     private double balance;
     private byte status;
     private Set<Bid> bids = new HashSet<Bid>(0);

    public Registration() {
    }

	
    public Registration(Car car, Participant participantByIdBuyer, Participant participantByIdDriver, Participant participantByIdOwner, Regatta regatta, double betEfficiency, double betFinishing, double secondsLap, short posSpeed, short posRacegrid, short posRace, short lapsRace, double prizeFinishing, double valueAuction, double valueBase, short posEfficiency, double prizeEfficiency, double balance, byte status) {
        this.car = car;
        this.participantByIdBuyer = participantByIdBuyer;
        this.participantByIdDriver = participantByIdDriver;
        this.participantByIdOwner = participantByIdOwner;
        this.regatta = regatta;
        this.betEfficiency = betEfficiency;
        this.betFinishing = betFinishing;
        this.secondsLap = secondsLap;
        this.posSpeed = posSpeed;
        this.posRacegrid = posRacegrid;
        this.posRace = posRace;
        this.lapsRace = lapsRace;
        this.prizeFinishing = prizeFinishing;
        this.valueAuction = valueAuction;
        this.valueBase = valueBase;
        this.posEfficiency = posEfficiency;
        this.prizeEfficiency = prizeEfficiency;
        this.balance = balance;
        this.status = status;
    }
    public Registration(Car car, Participant participantByIdBuyer, Participant participantByIdDriver, Participant participantByIdOwner, Regatta regatta, double betEfficiency, double betFinishing, double secondsLap, short posSpeed, short posRacegrid, short posRace, short lapsRace, double prizeFinishing, double valueAuction, double valueBase, short posEfficiency, double prizeEfficiency, double balance, byte status, Set<Bid> bids) {
       this.car = car;
       this.participantByIdBuyer = participantByIdBuyer;
       this.participantByIdDriver = participantByIdDriver;
       this.participantByIdOwner = participantByIdOwner;
       this.regatta = regatta;
       this.betEfficiency = betEfficiency;
       this.betFinishing = betFinishing;
       this.secondsLap = secondsLap;
       this.posSpeed = posSpeed;
       this.posRacegrid = posRacegrid;
       this.posRace = posRace;
       this.lapsRace = lapsRace;
       this.prizeFinishing = prizeFinishing;
       this.valueAuction = valueAuction;
       this.valueBase = valueBase;
       this.posEfficiency = posEfficiency;
       this.prizeEfficiency = prizeEfficiency;
       this.balance = balance;
       this.status = status;
       this.bids = bids;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Car getCar() {
        return this.car;
    }
    
    public void setCar(Car car) {
        this.car = car;
    }
    public Participant getParticipantByIdBuyer() {
        return this.participantByIdBuyer;
    }
    
    public void setParticipantByIdBuyer(Participant participantByIdBuyer) {
        this.participantByIdBuyer = participantByIdBuyer;
    }
    public Participant getParticipantByIdDriver() {
        return this.participantByIdDriver;
    }
    
    public void setParticipantByIdDriver(Participant participantByIdDriver) {
        this.participantByIdDriver = participantByIdDriver;
    }
    public Participant getParticipantByIdOwner() {
        return this.participantByIdOwner;
    }
    
    public void setParticipantByIdOwner(Participant participantByIdOwner) {
        this.participantByIdOwner = participantByIdOwner;
    }
    public Regatta getRegatta() {
        return this.regatta;
    }
    
    public void setRegatta(Regatta regatta) {
        this.regatta = regatta;
    }
    public double getBetEfficiency() {
        return this.betEfficiency;
    }
    
    public void setBetEfficiency(double betEfficiency) {
        this.betEfficiency = betEfficiency;
    }
    public double getBetFinishing() {
        return this.betFinishing;
    }
    
    public void setBetFinishing(double betFinishing) {
        this.betFinishing = betFinishing;
    }
    public double getSecondsLap() {
        return this.secondsLap;
    }
    
    public void setSecondsLap(double secondsLap) {
        this.secondsLap = secondsLap;
    }
    public short getPosSpeed() {
        return this.posSpeed;
    }
    
    public void setPosSpeed(short posSpeed) {
        this.posSpeed = posSpeed;
    }
    public short getPosRacegrid() {
        return this.posRacegrid;
    }
    
    public void setPosRacegrid(short posRacegrid) {
        this.posRacegrid = posRacegrid;
    }
    public short getPosRace() {
        return this.posRace;
    }
    
    public void setPosRace(short posRace) {
        this.posRace = posRace;
    }
    public short getLapsRace() {
        return this.lapsRace;
    }
    
    public void setLapsRace(short lapsRace) {
        this.lapsRace = lapsRace;
    }
    public double getPrizeFinishing() {
        return this.prizeFinishing;
    }
    
    public void setPrizeFinishing(double prizeFinishing) {
        this.prizeFinishing = prizeFinishing;
    }
    public double getValueAuction() {
        return this.valueAuction;
    }
    
    public void setValueAuction(double valueAuction) {
        this.valueAuction = valueAuction;
    }
    public double getValueBase() {
        return this.valueBase;
    }
    
    public void setValueBase(double valueBase) {
        this.valueBase = valueBase;
    }
    public short getPosEfficiency() {
        return this.posEfficiency;
    }
    
    public void setPosEfficiency(short posEfficiency) {
        this.posEfficiency = posEfficiency;
    }
    public double getPrizeEfficiency() {
        return this.prizeEfficiency;
    }
    
    public void setPrizeEfficiency(double prizeEfficiency) {
        this.prizeEfficiency = prizeEfficiency;
    }
    public double getBalance() {
        return this.balance;
    }
    
    public void setBalance(double balance) {
        this.balance = balance;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    public Set<Bid> getBids() {
        return this.bids;
    }
    
    public void setBids(Set<Bid> bids) {
        this.bids = bids;
    }




}


