package Tables;
// Generated 17-Jul-2024 12:43:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Variant generated by hbm2java
 */
public class Variant  implements java.io.Serializable {


     private Long id;
     private Venue venue;
     private String name;
     private double minWidth;
     private double length;
     private boolean metric;
     private long idCreator;
     private Set<Regatta> regattas = new HashSet<Regatta>(0);

    public Variant() {
    }

	
    public Variant(Venue venue, String name, double minWidth, double length, boolean metric, long idCreator) {
        this.venue = venue;
        this.name = name;
        this.minWidth = minWidth;
        this.length = length;
        this.metric = metric;
        this.idCreator = idCreator;
    }
    public Variant(Venue venue, String name, double minWidth, double length, boolean metric, long idCreator, Set<Regatta> regattas) {
       this.venue = venue;
       this.name = name;
       this.minWidth = minWidth;
       this.length = length;
       this.metric = metric;
       this.idCreator = idCreator;
       this.regattas = regattas;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Venue getVenue() {
        return this.venue;
    }
    
    public void setVenue(Venue venue) {
        this.venue = venue;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public double getMinWidth() {
        return this.minWidth;
    }
    
    public void setMinWidth(double minWidth) {
        this.minWidth = minWidth;
    }
    public double getLength() {
        return this.length;
    }
    
    public void setLength(double length) {
        this.length = length;
    }
    public boolean isMetric() {
        return this.metric;
    }
    
    public void setMetric(boolean metric) {
        this.metric = metric;
    }
    public long getIdCreator() {
        return this.idCreator;
    }
    
    public void setIdCreator(long idCreator) {
        this.idCreator = idCreator;
    }
    public Set<Regatta> getRegattas() {
        return this.regattas;
    }
    
    public void setRegattas(Set<Regatta> regattas) {
        this.regattas = regattas;
    }




}


