package Tables;
// Generated 17-Jul-2024 12:43:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Venue generated by hbm2java
 */
public class Venue  implements java.io.Serializable {


     private Long id;
     private Participant participant;
     private Provinceregion provinceregion;
     private String name;
     private double meridian;
     private double parallel;
     private long idCreator;
     private Set<Participant> participants = new HashSet<Participant>(0);
     private Set<Variant> variants = new HashSet<Variant>(0);

    public Venue() {
    }

	
    public Venue(Participant participant, Provinceregion provinceregion, String name, double meridian, double parallel, long idCreator) {
        this.participant = participant;
        this.provinceregion = provinceregion;
        this.name = name;
        this.meridian = meridian;
        this.parallel = parallel;
        this.idCreator = idCreator;
    }
    public Venue(Participant participant, Provinceregion provinceregion, String name, double meridian, double parallel, long idCreator, Set<Participant> participants, Set<Variant> variants) {
       this.participant = participant;
       this.provinceregion = provinceregion;
       this.name = name;
       this.meridian = meridian;
       this.parallel = parallel;
       this.idCreator = idCreator;
       this.participants = participants;
       this.variants = variants;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Participant getParticipant() {
        return this.participant;
    }
    
    public void setParticipant(Participant participant) {
        this.participant = participant;
    }
    public Provinceregion getProvinceregion() {
        return this.provinceregion;
    }
    
    public void setProvinceregion(Provinceregion provinceregion) {
        this.provinceregion = provinceregion;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public double getMeridian() {
        return this.meridian;
    }
    
    public void setMeridian(double meridian) {
        this.meridian = meridian;
    }
    public double getParallel() {
        return this.parallel;
    }
    
    public void setParallel(double parallel) {
        this.parallel = parallel;
    }
    public long getIdCreator() {
        return this.idCreator;
    }
    
    public void setIdCreator(long idCreator) {
        this.idCreator = idCreator;
    }
    public Set<Participant> getParticipants() {
        return this.participants;
    }
    
    public void setParticipants(Set<Participant> participants) {
        this.participants = participants;
    }
    public Set<Variant> getVariants() {
        return this.variants;
    }
    
    public void setVariants(Set<Variant> variants) {
        this.variants = variants;
    }




}


